// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-playground/cmd/gofrome-dao-scanlist/dao/internal"
)

// internalTestCertDeviceIdDao is internal type for wrapping internal DAO implements.
type internalTestCertDeviceIdDao = *internal.TestCertDeviceIdDao

// testCertDeviceIdDao is the data access object for table test_cert_deviceId.
// You can define custom methods on it to extend its functionality as you wish.
type testCertDeviceIdDao struct {
	internalTestCertDeviceIdDao
}

var (
	// TestCertDeviceId is globally public accessible object for table test_cert_deviceId operations.
	TestCertDeviceId = testCertDeviceIdDao{
		internal.NewTestCertDeviceIdDao(),
	}
)

// Fill with you ideas below.
