// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Id       int64  `json:"id"`
	Name     string `json:"name"`
	Token    string `json:"token"`
	ExpireAt uint64 `json:"expireAt"`
}

type InfoReq struct {
	Id int64 `json:"id"`
}

type InfoResp struct {
	Id      int64  `json:"id"`
	Name    string `json:"name"`
	Address string `json:"addrress"`
}

type SetInfoReq struct {
	Id      int64  `json:"id"`
	Name    string `json:"name"`
	Address string `json:"addrress"`
}

type SetInfoResp struct {
}
