// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// TestCertDeviceId is the golang structure of table test_cert_deviceId for DAO operations like Where/Data.
type TestCertDeviceId struct {
	g.Meta    `orm:"table:test_cert_deviceId, do:true"`
	Id        interface{} //
	Identity  interface{} // 用户定义的证书标识
	DeviceId  interface{} // 设备号
	CreatedAt *gtime.Time // 创建时间
	UpdatedAt *gtime.Time // 更新时间
}
