// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// TestCertInfo is the golang structure of table test_cert_info for DAO operations like Where/Data.
type TestCertInfo struct {
	g.Meta            `orm:"table:test_cert_info, do:true"`
	Id                interface{} //
	Version           interface{} // 版本号
	Identity          interface{} // 用户定义的证书标识
	CertType          interface{} // 证书类型
	IssuerIdentity    interface{} // 颁发机构标识
	Subject           interface{} // 证书主体信息
	ValidityNotbefore *gtime.Time // 证书有效期开始
	ValidityNotafter  *gtime.Time // 证书有效期结束
	CustomerName      interface{} // 用户名称
	CustomerIdcard    interface{} // 用户身份证号
	CustomerId        interface{} // 客户id
	SerialNumber      interface{} // 证书序列号
	Status            interface{} // 证书状态
	CreatedAt         *gtime.Time // 创建时间
	UpdatedAt         *gtime.Time // 更新时间
}
