// 声明 proto 语法版本，固定值

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.3
// source: cmd/zero-demo/rpc/greet.proto

// proto 包名

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 定义结构体
type SayHelloReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SayHelloReq) Reset() {
	*x = SayHelloReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_zero_demo_rpc_greet_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SayHelloReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloReq) ProtoMessage() {}

func (x *SayHelloReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_zero_demo_rpc_greet_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloReq.ProtoReflect.Descriptor instead.
func (*SayHelloReq) Descriptor() ([]byte, []int) {
	return file_cmd_zero_demo_rpc_greet_proto_rawDescGZIP(), []int{0}
}

type SayHelloResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SayHelloResp) Reset() {
	*x = SayHelloResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_zero_demo_rpc_greet_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SayHelloResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloResp) ProtoMessage() {}

func (x *SayHelloResp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_zero_demo_rpc_greet_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloResp.ProtoReflect.Descriptor instead.
func (*SayHelloResp) Descriptor() ([]byte, []int) {
	return file_cmd_zero_demo_rpc_greet_proto_rawDescGZIP(), []int{1}
}

type SendMessageReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *SendMessageReq) Reset() {
	*x = SendMessageReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_zero_demo_rpc_greet_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageReq) ProtoMessage() {}

func (x *SendMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_zero_demo_rpc_greet_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageReq.ProtoReflect.Descriptor instead.
func (*SendMessageReq) Descriptor() ([]byte, []int) {
	return file_cmd_zero_demo_rpc_greet_proto_rawDescGZIP(), []int{2}
}

func (x *SendMessageReq) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SendMessageResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *SendMessageResp) Reset() {
	*x = SendMessageResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_zero_demo_rpc_greet_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendMessageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResp) ProtoMessage() {}

func (x *SendMessageResp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_zero_demo_rpc_greet_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResp.ProtoReflect.Descriptor instead.
func (*SendMessageResp) Descriptor() ([]byte, []int) {
	return file_cmd_zero_demo_rpc_greet_proto_rawDescGZIP(), []int{3}
}

func (x *SendMessageResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetMessageReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetMessageReq) Reset() {
	*x = GetMessageReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_zero_demo_rpc_greet_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageReq) ProtoMessage() {}

func (x *GetMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_zero_demo_rpc_greet_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageReq.ProtoReflect.Descriptor instead.
func (*GetMessageReq) Descriptor() ([]byte, []int) {
	return file_cmd_zero_demo_rpc_greet_proto_rawDescGZIP(), []int{4}
}

func (x *GetMessageReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetMessageResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *GetMessageResp) Reset() {
	*x = GetMessageResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_zero_demo_rpc_greet_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMessageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageResp) ProtoMessage() {}

func (x *GetMessageResp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_zero_demo_rpc_greet_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageResp.ProtoReflect.Descriptor instead.
func (*GetMessageResp) Descriptor() ([]byte, []int) {
	return file_cmd_zero_demo_rpc_greet_proto_rawDescGZIP(), []int{5}
}

func (x *GetMessageResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_cmd_zero_demo_rpc_greet_proto protoreflect.FileDescriptor

var file_cmd_zero_demo_rpc_greet_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x63, 0x6d, 0x64, 0x2f, 0x7a, 0x65, 0x72, 0x6f, 0x2d, 0x64, 0x65, 0x6d, 0x6f, 0x2f,
	0x72, 0x70, 0x63, 0x2f, 0x67, 0x72, 0x65, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x67, 0x72, 0x65, 0x65, 0x74, 0x22, 0x0d, 0x0a, 0x0b, 0x53, 0x61, 0x79, 0x48, 0x65, 0x6c,
	0x6c, 0x6f, 0x52, 0x65, 0x71, 0x22, 0x0e, 0x0a, 0x0c, 0x53, 0x61, 0x79, 0x48, 0x65, 0x6c, 0x6c,
	0x6f, 0x52, 0x65, 0x73, 0x70, 0x22, 0x2a, 0x0a, 0x0e, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0x29, 0x0a, 0x0f, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x1f, 0x0a, 0x0d,
	0x47, 0x65, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2a, 0x0a,
	0x0e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0xc3, 0x01, 0x0a, 0x05, 0x47, 0x72,
	0x65, 0x65, 0x74, 0x12, 0x3c, 0x0a, 0x0b, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x15, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x67, 0x72, 0x65, 0x65,
	0x74, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x3b, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x14, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x2e, 0x47, 0x65,
	0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x30, 0x01, 0x12, 0x3f,
	0x0a, 0x0b, 0x50, 0x75, 0x73, 0x68, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x15, 0x2e,
	0x67, 0x72, 0x65, 0x65, 0x74, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x2e, 0x47, 0x65, 0x74,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x28, 0x01, 0x30, 0x01, 0x42,
	0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cmd_zero_demo_rpc_greet_proto_rawDescOnce sync.Once
	file_cmd_zero_demo_rpc_greet_proto_rawDescData = file_cmd_zero_demo_rpc_greet_proto_rawDesc
)

func file_cmd_zero_demo_rpc_greet_proto_rawDescGZIP() []byte {
	file_cmd_zero_demo_rpc_greet_proto_rawDescOnce.Do(func() {
		file_cmd_zero_demo_rpc_greet_proto_rawDescData = protoimpl.X.CompressGZIP(file_cmd_zero_demo_rpc_greet_proto_rawDescData)
	})
	return file_cmd_zero_demo_rpc_greet_proto_rawDescData
}

var file_cmd_zero_demo_rpc_greet_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_cmd_zero_demo_rpc_greet_proto_goTypes = []interface{}{
	(*SayHelloReq)(nil),     // 0: greet.SayHelloReq
	(*SayHelloResp)(nil),    // 1: greet.SayHelloResp
	(*SendMessageReq)(nil),  // 2: greet.SendMessageReq
	(*SendMessageResp)(nil), // 3: greet.SendMessageResp
	(*GetMessageReq)(nil),   // 4: greet.GetMessageReq
	(*GetMessageResp)(nil),  // 5: greet.GetMessageResp
}
var file_cmd_zero_demo_rpc_greet_proto_depIdxs = []int32{
	2, // 0: greet.Greet.SendMessage:input_type -> greet.SendMessageReq
	4, // 1: greet.Greet.GetMessage:input_type -> greet.GetMessageReq
	2, // 2: greet.Greet.PushMessage:input_type -> greet.SendMessageReq
	3, // 3: greet.Greet.SendMessage:output_type -> greet.SendMessageResp
	5, // 4: greet.Greet.GetMessage:output_type -> greet.GetMessageResp
	5, // 5: greet.Greet.PushMessage:output_type -> greet.GetMessageResp
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cmd_zero_demo_rpc_greet_proto_init() }
func file_cmd_zero_demo_rpc_greet_proto_init() {
	if File_cmd_zero_demo_rpc_greet_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cmd_zero_demo_rpc_greet_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SayHelloReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_zero_demo_rpc_greet_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SayHelloResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_zero_demo_rpc_greet_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendMessageReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_zero_demo_rpc_greet_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendMessageResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_zero_demo_rpc_greet_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMessageReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_zero_demo_rpc_greet_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMessageResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cmd_zero_demo_rpc_greet_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cmd_zero_demo_rpc_greet_proto_goTypes,
		DependencyIndexes: file_cmd_zero_demo_rpc_greet_proto_depIdxs,
		MessageInfos:      file_cmd_zero_demo_rpc_greet_proto_msgTypes,
	}.Build()
	File_cmd_zero_demo_rpc_greet_proto = out.File
	file_cmd_zero_demo_rpc_greet_proto_rawDesc = nil
	file_cmd_zero_demo_rpc_greet_proto_goTypes = nil
	file_cmd_zero_demo_rpc_greet_proto_depIdxs = nil
}
