// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-playground/cmd/gofrome-dao-scanlist/dao/internal"
)

// internalTestCertInfoDao is internal type for wrapping internal DAO implements.
type internalTestCertInfoDao = *internal.TestCertInfoDao

// testCertInfoDao is the data access object for table test_cert_info.
// You can define custom methods on it to extend its functionality as you wish.
type testCertInfoDao struct {
	internalTestCertInfoDao
}

var (
	// TestCertInfo is globally public accessible object for table test_cert_info operations.
	TestCertInfo = testCertInfoDao{
		internal.NewTestCertInfoDao(),
	}
)

// Fill with you ideas below.
