// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// TestCertInfo is the golang structure for table test_cert_info.
type TestCertInfo struct {
	Id                uint64      `json:"id"                ` //
	Version           uint        `json:"version"           ` // 版本号
	Identity          string      `json:"identity"          ` // 用户定义的证书标识
	CertType          string      `json:"certType"          ` // 证书类型
	IssuerIdentity    string      `json:"issuerIdentity"    ` // 颁发机构标识
	Subject           string      `json:"subject"           ` // 证书主体信息
	ValidityNotbefore *gtime.Time `json:"validityNotbefore" ` // 证书有效期开始
	ValidityNotafter  *gtime.Time `json:"validityNotafter"  ` // 证书有效期结束
	CustomerName      string      `json:"customerName"      ` // 用户名称
	CustomerIdcard    string      `json:"customerIdcard"    ` // 用户身份证号
	CustomerId        uint64      `json:"customerId"        ` // 客户id
	SerialNumber      string      `json:"serialNumber"      ` // 证书序列号
	Status            string      `json:"status"            ` // 证书状态
	CreatedAt         *gtime.Time `json:"createdAt"         ` // 创建时间
	UpdatedAt         *gtime.Time `json:"updatedAt"         ` // 更新时间
}
